### ISSUE TITLE
Suppor to prefix user namespaces

### ISSUE THREAD

**Issue by gustavosr98** [canonical/kubeflow-profiles-operator#242]
### Context

A Kubernetes cluster can have multiple namespaces
One way to organize and avoid conflict of a username with existing namespaces is
To have the option to prefix the user namespaces with an arbitraty value

### What needs to get done

Add an optional configuation option to prefix kubernetes namespaces used for Kubeflow profiles

Instead of
```yaml
apiVersion: kubeflow.org/v1
kind: Profile
metadata:
  name: <username>
spec:
  owner:
    kind: User
    name: <username>
```

To have the optional config parameter eg. `profiles-prefix=kubeflow-`
```yaml
apiVersion: kubeflow.org/v1
kind: Profile
metadata:
  name: ${prefix}${username}
spec:
  owner:
    kind: User
    name: <username>
```

### Definition of Done

When running `$ kubectl get profile` or `$ kubectl get ns` you see the prefix
